spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: test
    password:
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: create
  h2:
    console:
      enabled: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

redis:
  database: DevelhopeRedisExercise
  password: VsA5xRPjTsmjski6z65AMkM057jOFGNU
  host: redis-10054.c100.us-east-1-4.ec2.cloud.redislabs.com
  port: 10054
