server:
  port: 5000

---
spring:
  config:
    activate:
      on-profile: prod
customVar: 2
server:
  port: 7070

---
spring:
  config:
    activate:
      on-profile: test
customVar: 42

server:
  port: 4000
