
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cruddb
    username: nic
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update