spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: mauijk@gmail.com
    password: pecora
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

