spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: monopatino@gmail.com
    password: eletrico
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

