spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: xpulvi42@gmail.com
    password: mqfvauswizvlmntz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

