spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: martelo@gmail.com
    password: doro
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
